### PR TITLE
Added Credentials based login

### LINKED ISSUE #16: Add Credential based login
Providing login using user credentials.

### PR DESCRIPTION
**Pull request by pranjulps3**
Closes #16

### CODE REVIEW

**Comment by Samy-33** [comment]
@pranjulps3, why are two requests being sent while clicking on **login**?

**Comment by pranjulps3** [comment]
> why are two requests being sent while clicking on login?

Because one is to fetch the token and the other to get user details.

**Comment by Samy-33** [comment]
Both at `/auth/token/`?

**Comment by pranjulps3** [comment]
Issue with subscriber reuse. Thought I removed all that are used outside. Removing all immediately.

**Comment by pranjulps3** [comment]
**[Fix-Description]**
**Cause:** Multiple subscriptions made to a cold `HTTP:GET` Observable made it get called for each subscription.
**Solution:**
Remapped all the Observable objects to use `pipe` with `map` for services and return the pipe instead of the request itself.

**Review by Samy-33 — APPROVED** [review]

**Pull request merged**
