### PR TITLE
Added social authentication (except GitHub #11)

### LINKED ISSUE #7: Implement social auth login
Steps to follow:  
  * Add `href` on the login/signup icons to third party oauth handling urls.  
  * Add `redirect_uri` to the page that handles token returned from the thirdparty oauth servers.
  * After receiving the token and other required params, make a request to the API with these values and handle the storage of return on **Auth-token, refresh token and user object**.    
## UPDATE  
Using `angularx-social-login` which automatically handles the social login for `facebook` and `google` for now.

### PR DESCRIPTION
**Pull request by pranjulps3**
Closes #7

### CODE REVIEW

**Comment by Samy-33** [comment]
User doesn't login to google and it still shows user has logged in. PFA

**Comment by Samy-33** [comment]
Can you please add some kind of information which will validate which user has been logged in/signed up?

**Comment by pranjulps3** [comment]
> 
> 
> Can you please add some kind of information which will validate which user has been logged in/signed up?

After login the login button will become logout. 

> User doesn't login to google and it still shows user has logged in. PFA

Just pushing a fix to that.

**Comment by pranjulps3** [comment]
Added fix to the prior issue. Please review @Samy-33 sir

**Review by Samy-33 — APPROVED** [review]

**Pull request merged**
